name: Build LaTeX document
on: [push]
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir output
      - uses: docker://pandoc/core:latest
        with:
          args: >-
            -s texproject/main.tex 
            -f latex 
            -t epub2 
            -o output/main.epub
            --bibliography texproject/references.bib
            --csl aps.csl
      - uses: actions/upload-artifact@main
        with:
          name: manuscript
          path: output
