name: Build LaTeX document
on: [push]
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd texproject
      - run: mkdir output
      - uses: docker://pandoc/core:latest
        with:
          args: >-
            -s main.tex 
            -f latex 
            -t epub2 
            -o output/main.epub
            --bibliography references.bib
            --csl ../aps.csl
            --citeproc
            --mathml
      - uses: actions/upload-artifact@main
        with:
          name: manuscript
          path: texproject/output
