name: Build HTML document
on: [push]
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir output
      - uses: docker://pandoc/core:latest
        with:
          args: >-
            -s texproject/main.tex 
            -f latex 
            -t html5 
            -o output/main.html
            --bibliography texproject/references.bib
            --csl aps.csl
            --citeproc
            --mathml
      - uses: actions/upload-artifact@main
        with:
          name: html-manuscript
          path: output
